defaults:
  - data: dataset
  - preprocess: base
  - train: yolov8n
  - infer: default
  - postprocess: default
  - logging: mlflow
  - _self_

seed: 42

paths:
  plots_dir: plots
  artifacts_dir: outputs

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
